const SUPABASE_URL='https://mhyppitteqephfcqjlrx.supabase.co';
const SUPABASE_KEY='sb_publishable_QeZD6jeTtwrNe2sZi5U5PQ_r7K66zhL';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let mode='login', session=null, profile=null, transactions=[], payments=[], events=[], notifications=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' ');
const money=(n,c)=>c==='USDT'?'₮'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'₦'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
const today=()=>new Date().toISOString().slice(0,10);
function showHome(){['home'].forEach(id=>$(id).classList.remove('hidden'));['auth','dashboard'].forEach(id=>$(id).classList.add('hidden'));$('navActions').innerHTML=session?'<button class="secondary" onclick="signOut()">Log out</button>':''}
function openAuth(m){$('home').classList.add('hidden');$('dashboard').classList.add('hidden');$('auth').classList.remove('hidden');setMode(m);$('navActions').innerHTML=''}
function setMode(m){mode=m;$('loginTab').classList.toggle('active',m==='login');$('registerTab').classList.toggle('active',m==='register');$('resetTab').classList.toggle('active',m==='reset');$('nameField').classList.toggle('hidden',m!=='register');$('nicknameField').classList.toggle('hidden',m!=='register');$('roleField').classList.toggle('hidden',m!=='register');$('passwordField').classList.toggle('hidden',m==='reset');$('authTitle').textContent=m==='login'?'Log in':m==='register'?'Create account':'Reset password';$('authSubtitle').textContent=m==='login'?'Access your private dashboard.':m==='register'?'Create an INVESTOR or TRADER account.':'Enter your email and we will send a secure reset link.';$('authSubmit').textContent=m==='login'?'Log in':m==='register'?'Create account':'Send reset link';$('authMessage').textContent='';$('password').value='';}
function togglePassword(){const p=$('password');p.type=p.type==='password'?'text':'password';$('togglePassword').textContent=p.type==='password'?'Show':'Hide'}
function validNick(n){return /^[A-Za-z0-9_.-]{2,40}$/.test(n)}
$('loginTab').onclick=()=>setMode('login');$('registerTab').onclick=()=>setMode('register');$('resetTab').onclick=()=>setMode('reset');$('togglePassword').onclick=togglePassword;
$('authForm').addEventListener('submit',async e=>{e.preventDefault();$('authMessage').textContent='Please wait...';$('authMessage').className='message';const email=$('email').value.trim().toLowerCase();
 if(mode==='reset'){const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$('authMessage').style.color=error?'#b42318':'#176b3a';$('authMessage').textContent=error?error.message:'If an account exists for that email, a reset link has been sent.';return}
 const password=$('password').value;
 if(mode==='register'){const name=$('fullName').value.trim(),nickname=$('nickname').value.trim(),role=$('role').value;if(name.length<2){$('authMessage').textContent='Enter your full name.';return}if(!validNick(nickname)){ $('authMessage').textContent='Nickname must be 2–40 characters: letters, numbers, dot, underscore or hyphen.';return}if(password.length<8){$('authMessage').textContent='Password must be at least 8 characters.';return}
  const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name:name,nickname,role},emailRedirectTo:location.origin+location.pathname}});if(error){$('authMessage').textContent=error.message;return}if(data.session){session=data.session;await loadApp()}else{$('authMessage').style.color='#176b3a';$('authMessage').textContent='Account created. Check your email to confirm, then log in.'}
 }else{const {data,error}=await db.auth.signInWithPassword({email,password});if(error){$('authMessage').textContent=error.message;return}session=data.session;await loadApp()}
});
async function signOut(){await db.auth.signOut();session=null;profile=null;transactions=[];payments=[];events=[];notifications=[];showHome();toast('Logged out')}
async function loadApp(){const {data:{session:s}}=await db.auth.getSession();session=s;if(!session){showHome();return}const r=await db.from('profiles').select('*').eq('id',session.user.id).maybeSingle();profile=r.data;if(r.error||!profile){$('authMessage').textContent='Your profile could not be loaded. Please contact support.';return}$('home').classList.add('hidden');$('auth').classList.add('hidden');$('dashboard').classList.remove('hidden');$('navActions').innerHTML='<button class="secondary" onclick="signOut()">Log out</button>';$('welcome').textContent='Welcome, '+(profile.full_name||'User');$('roleLabel').textContent=profile.role+' DASHBOARD';$('dashMessage').textContent=profile.role==='INVESTOR'?'Manage your investments and confirm received payments.':'Manage trading obligations and your own investments.';$('newBtn').classList.remove('hidden');await refresh()}
async function refresh(){const tr=await db.from('transactions').select('*').order('created_at',{ascending:false});if(tr.error){toast(tr.error.message);return}transactions=tr.data||[];const ids=transactions.map(t=>t.id);if(ids.length){const [p,e,n]=await Promise.all([db.from('payments').select('*').in('transaction_id',ids).order('created_at',{ascending:true}),db.from('transaction_events').select('*').in('transaction_id',ids).order('created_at',{ascending:true}),db.from('notifications').select('*').order('created_at',{ascending:false}).limit(30)]);payments=p.data||[];events=e.data||[];notifications=n.data||[]}else{payments=[];events=[];notifications=[]}renderAll()}
function paymentTotal(id){return payments.filter(p=>p.transaction_id===id&&p.confirmation_status==='CONFIRMED').reduce((a,p)=>a+Number(p.amount||0),0)}
function txStatus(t){if(t.confirmation_status!=='CONFIRMED')return t.confirmation_status;const paid=paymentTotal(t.id),left=Math.max(0,Number(t.expected_payout)-paid);if(left<=0)return'PAID';if(t.expected_payout_date<today())return'OVERDUE';if(paid>0)return'PARTIALLY_PAID';return'NOT_PAID'}
function statusClass(s){return s==='CONFIRMED'||s==='PAID'?'confirmed':s==='DISPUTED'||s==='OVERDUE'?'disputed':'pending'}
function renderAll(){const mine=transactions.filter(t=>t.investor_id===session.user.id),ob=transactions.filter(t=>t.trader_id===session.user.id&&t.investor_id!==session.user.id);const sum=(arr,c,key)=>arr.filter(t=>t.currency===c).reduce((a,t)=>a+Number(t[key]||0),0);const outstanding=arr=>arr.filter(t=>t.confirmation_status==='CONFIRMED').reduce((a,t)=>a+Math.max(0,Number(t.expected_payout)-paymentTotal(t.id)),0);$('myNgn').textContent=money(sum(mine,'NGN','amount_invested'),'NGN');$('myUsdt').textContent=money(sum(mine,'USDT','amount_invested'),'USDT');$('obNgn').textContent=money(sum(ob,'NGN','amount_invested'),'NGN');$('obUsdt').textContent=money(sum(ob,'USDT','amount_invested'),'USDT');$('outNgn').textContent=money(outstanding(mine.filter(t=>t.currency==='NGN')),'NGN');$('outUsdt').textContent=money(outstanding(mine.filter(t=>t.currency==='USDT')),'USDT');$('obOutNgn').textContent=money(outstanding(ob.filter(t=>t.currency==='NGN')),'NGN');$('obOutUsdt').textContent=money(outstanding(ob.filter(t=>t.currency==='USDT')),'USDT');renderPending();renderTable();renderNotifications();}
function renderPending(){const pending=transactions.filter(t=>t.confirmation_status==='PENDING'&&profile.role==='TRADER'&&t.investor_id!==session.user.id);$('pendingArea').innerHTML=pending.length?'<h3>Awaiting your confirmation</h3>'+pending.map(t=>`<div class="pendingCard"><div><b>${esc(t.transaction_id)}</b><br>${esc(t.investor_name)} · ${money(t.amount_invested,t.currency)} · ROI ${Number(t.roi_percent)}%</div><div class="actions"><button class="smallBtn primarySmall" onclick="confirmTx('${t.id}','CONFIRMED')">Confirm</button><button class="smallBtn" onclick="confirmTx('${t.id}','DISPUTED')">Dispute</button></div></div>`).join(''):''}
function renderTable(){const q=norm($('searchBox').value);const rows=transactions.filter(t=>!q||norm([t.transaction_id,t.investor_name,t.trader_name,t.currency].join(' ')).includes(q));$('txBody').innerHTML=rows.length?rows.map(t=>{const own=t.investor_id===session.user.id;const type=profile.role==='TRADER'?(own?'MY INVESTMENT':'TRADING OBLIGATION'):'MY INVESTMENT';const other=profile.role==='INVESTOR'?t.trader_name:(own?t.trader_name:t.investor_name);const s=txStatus(t);const action=(t.trader_id===session.user.id&&t.confirmation_status==='CONFIRMED')?`<button class="smallBtn" onclick="recordPayment('${t.id}')">Record payment</button>`:'';const receipt=profile.role==='INVESTOR'?payments.filter(p=>p.transaction_id===t.id&&p.confirmation_status==='PENDING_RECEIPT').map(p=>`<button class="smallBtn" onclick="confirmPayment('${p.id}','CONFIRMED')">Confirm receipt ${money(p.amount,t.currency)}</button><button class="smallBtn" onclick="confirmPayment('${p.id}','DISPUTED')">Dispute</button>`).join(''):'';return `<tr><td><b>${esc(t.transaction_id)}</b><br><small>${type}</small></td><td>${esc(other)}</td><td>${t.currency}</td><td>${money(t.amount_invested,t.currency)}</td><td>${Number(t.roi_percent)}%</td><td><span class="status ${statusClass(s)}">${esc(s.replace('_',' '))}</span></td><td><div class="actions"><button class="smallBtn" onclick="details('${t.id}')">Details</button>${action}${receipt}</div></td></tr>`}).join(''):'<tr><td colspan="7" class="empty">No transactions yet.</td></tr>'}
function renderNotifications(){const ns=notifications.filter(n=>n.user_id===session.user.id);$('notifications').innerHTML=ns.length?ns.slice(0,8).map(n=>`<div class="notice ${n.read_at?'':'unread'}"><b>${esc(n.title)}</b><br><span>${esc(n.body)}</span></div>`).join(''):'<div class="empty">No notifications.</div>'}
async function confirmTx(id,decision){const {error}=await db.rpc('confirm_transaction',{tx_id:id,decision});if(error){toast(error.message);return}toast('Transaction '+decision.toLowerCase());await refresh()}
async function confirmPayment(id,decision){const {error}=await db.rpc('confirm_payment',{payment_id:id,decision});if(error){toast(error.message);return}toast('Payment '+decision.toLowerCase());await refresh()}
async function recordPayment(id){const t=transactions.find(x=>x.id===id);const n=Number(prompt('Enter amount paid/returned:')||0);if(!n||n<=0){toast('Enter a valid amount');return}const left=Math.max(0,Number(t.expected_payout)-paymentTotal(id));if(n>left){toast('Payment exceeds outstanding balance');return}const note=prompt('Optional payment note:')||null;const {error}=await db.rpc('record_payment',{tx_id:id,amount:n,note});if(error){toast(error.message);return}toast('Payment recorded; investor must confirm receipt');await refresh()}
function addBusinessDays(date,days){let d=new Date(date+'T12:00:00'),n=Number(days);while(n){d.setDate(d.getDate()+1);if(d.getDay()>0&&d.getDay()<6)n--}return d.toISOString().slice(0,10)}
function dayName(date){return new Date(date+'T12:00:00').toLocaleDateString('en-NG',{weekday:'long'})}
function calc(){const a=Number($('amount').value||0),r=Number($('roi').value||0),d=$('investmentDate').value,term=$('term').value,c=$('currency').value;if(!a||!d){$('preview').textContent='Expected profit and payout will appear here.';return}const p=a*r/100,total=a+p,due=addBusinessDays(d,term);$('preview').innerHTML=`Profit <b>${money(p,c)}</b> · Payout <b>${money(total,c)}</b> · Due <b>${due}</b> (${dayName(due)})`}
['amount','roi','investmentDate','term','currency'].forEach(id=>$(id).addEventListener('input',calc));
$('investmentForm').addEventListener('submit',async e=>{e.preventDefault();const traderName=$('traderName').value.trim(),a=Number($('amount').value),r=Number($('roi').value),d=$('investmentDate').value,term=Number($('term').value),c=$('currency').value;if(!traderName||!a||a<=0||r<0||!d||![3,7].includes(term)){toast('Complete all investment fields');return}if(norm(traderName)===norm(profile.full_name)||norm(traderName)===norm(profile.nickname)){toast('You cannot invest with yourself as the trader');return}$('investmentMessage').textContent='Creating...';const {data,error}=await db.rpc('create_transaction',{trader_name_input:traderName,currency_input:c,amount_input:a,roi_input:r,investment_date_input:d,term_input:term});if(error){$('investmentMessage').textContent=error.message;return}$('investmentMessage').style.color='#176b3a';$('investmentMessage').textContent=`Created ${data.transaction_id}. Awaiting trader confirmation.`;toast('Investment created');$('investmentForm').reset();$('investmentDate').value=today();calc();await refresh()});
async function details(id){const t=transactions.find(x=>x.id===id);if(!t)return;const ps=payments.filter(p=>p.transaction_id===id),es=events.filter(e=>e.transaction_id===id);$('modalTitle').textContent=t.transaction_id;$('modalBody').innerHTML=`<div class="detailGrid"><div><b>Investor</b><br>${esc(t.investor_name)}</div><div><b>Trader</b><br>${esc(t.trader_name)}</div><div><b>Currency</b><br>${t.currency}</div><div><b>Amount</b><br>${money(t.amount_invested,t.currency)}</div><div><b>ROI</b><br>${Number(t.roi_percent)}%</div><div><b>Expected profit</b><br>${money(t.expected_profit,t.currency)}</div><div><b>Expected payout</b><br>${money(t.expected_payout,t.currency)}</div><div><b>Investment date</b><br>${t.investment_date} (${esc(t.investment_day)})</div><div><b>Expected payout date</b><br>${t.expected_payout_date} (${esc(t.payout_day)})</div><div><b>Payment status</b><br>${txStatus(t).replace('_',' ')}</div></div><h3>Payments</h3>${ps.length?ps.map(p=>`<div class="history"><b>${money(p.amount,t.currency)}</b> · ${esc(p.confirmation_status)} · ${new Date(p.created_at).toLocaleString()}</div>`).join(''):'<div class="muted">No payments recorded.</div>'}<h3>History</h3>${es.length?es.map(e=>`<div class="history"><b>${esc(e.event_type)}</b><br>${esc(e.description)}<br><small>${new Date(e.created_at).toLocaleString()}</small></div>`).join(''):'<div class="muted">No history yet.</div>'}`;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
$('newBtn').onclick=()=>{$('investmentPanel').classList.remove('hidden');$('investmentDate').value=today();calc();$('investmentPanel').scrollIntoView({behavior:'smooth'})};$('closeInvestment').onclick=()=>{$('investmentPanel').classList.add('hidden')};$('closeModal').onclick=closeModal;
db.auth.onAuthStateChange((event,s)=>{session=s;if(event==='SIGNED_OUT')showHome();if(event==='PASSWORD_RECOVERY'){openAuth('reset');$('passwordField').classList.remove('hidden');$('authSubmit').textContent='Set new password';$('authSubtitle').textContent='Choose a new password for your account.';$('authForm').onsubmit=async e=>{e.preventDefault();const p=$('password').value;if(p.length<8){$('authMessage').textContent='Password must be at least 8 characters.';return}const {error}=await db.auth.updateUser({password:p});if(error){$('authMessage').textContent=error.message;return}toast('Password updated');await loadApp()}}});
$('investmentDate').value=today();
loadApp();
